# Generated by Django 5.2.6 on 2025-09-09 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Local')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf_saran', models.CharField(max_length=20, unique=True, verbose_name='CPF ou SARAN')),
            ],
        ),
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, unique=True, verbose_name='Descrição da Chave')),
                ('disponivel', models.BooleanField(default=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chaves', to='claviculario_app.local')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateTimeField(verbose_name='Data e Hora da Retirada')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora da Devolução')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='claviculario_app.chave')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='claviculario_app.pessoa')),
            ],
        ),
    ]
