# Generated by Django 5.2.6 on 2025-09-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claviculario_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='pin',
            field=models.CharField(default=1234, max_length=128, verbose_name='Pin de Confirmação'),
            preserve_default=False,
        ),
    ]
