# Generated by Django 5.2.6 on 2025-09-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claviculario_app', '0002_pessoa_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='previsao_devolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Previsão de Devolução'),
        ),
    ]
