# Generated by Django 5.2.6 on 2025-09-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claviculario_app', '0003_emprestimo_previsao_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Chave ativa?'),
        ),
    ]
