# Generated by Django 5.2.6 on 2025-09-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claviculario_app', '0004_chave_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Local ativo?'),
        ),
    ]
