# Generated by Django 5.2.6 on 2025-10-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claviculario_app', '0005_local_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Pessoa ativa?'),
        ),
    ]
