# Generated by Django 5.2.6 on 2025-10-11 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claviculario_app', '0006_pessoa_ativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chave',
            options={'ordering': ['descricao'], 'verbose_name': 'Chave', 'verbose_name_plural': 'Chaves'},
        ),
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-data_retirada'], 'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'ordering': ['nome'], 'verbose_name': 'Local', 'verbose_name_plural': 'Locais'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome'], 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Unidade')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo da Unidade')),
                ('cor_tema', models.CharField(default='#0d6efd', max_length=7, verbose_name='Cor Principal do Tema')),
                ('membros', models.ManyToManyField(blank=True, related_name='unidades_membro', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
    ]
